//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaManager
{
    using System;
    using System.Collections.Generic;
    using NinjaManager.ViewModel;

    public partial class Equipment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Strength { get; set; }
        public int Intelligence { get; set; }
        public int Agility { get; set; }
        public int CategoryId { get; set; }
        public int Price { get; set; }
    
        public virtual EquipmentCategory EquipmentCategory { get; set; }

        internal EquipmentViewModel ToPoCo()
        {
            return new EquipmentViewModel(this);
        }
    }
}
